recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    #Home
    path('', include('recipes.urls')),
    #Login
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, search, about, add_recipe

app_name = 'recipes'

urlpatterns = [
   path('', home),
   path('recipes/list/', RecipeListView.as_view(), name='list'),
   path('recipes/list/<pk>', RecipeDetailView.as_view(), name='detail'),
   path('recipes/search/', search, name='search'),
   path("recipes/add_recipe", add_recipe, name="add_recipe"),
   path("recipes/about/", about, name="about"),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Recipe (models.Model):
    name = models.CharField(max_length=50)
    cooking_time = models.FloatField(help_text='In minutes')
    ingredients = models.CharField(max_length=225)
    description = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def get_absolute_url(self):
       return reverse ('recipes:detail', kwargs={'pk': self.pk})

    #Difficulty calculation
    @property
    def difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 10 and len(ingredients) < 4:
            return 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            return 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            return 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            return 'Hard'
        return "Unknown"

    def __str__(self):
        return str(self.name)

recipes/forms.py
from django import forms
from .models import Recipe

SEARCH_CHOICES = [
    ("name", "Recipe Name"),
    ("cooking_time", "Cooking Time (minutes)"),
    ("difficulty", "Difficulty"),
]

class RecipeSearchForm(forms.Form):
    search_by = forms.ChoiceField(choices=SEARCH_CHOICES, required=True, label="Search by")
    search_term = forms.CharField(max_length=100, required=False, label="Search term")
    cooking_time = forms.IntegerField(required=False, label="Cooking Time (minutes)")
    difficulty = forms.ChoiceField(
        choices=[
            ("Easy", "Easy"),
            ("Medium", "Medium"),
            ("Intermediate", "Intermediate"),
            ("Hard", "Hard"),
        ],
        required=False,
        label="Difficulty"
    )

class NewRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "cooking_time",
            "ingredients",
            "description",
            "pic"
              ]

recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Recipe
import pandas as pd
from .forms import RecipeSearchForm, NewRecipeForm
from .utils import get_chart


# Create your views here.

def home(request):
   return render(request, 'recipes/recipes_home.html')

#Use Listview for listing the recipes
class RecipeListView(LoginRequiredMixin, ListView):  
    model = Recipe 
    template_name = 'recipes/recipe_overview.html'

#Use DetailView for the individual recipe page
class RecipeDetailView(LoginRequiredMixin, DetailView): 
    model = Recipe
    template_name = 'recipes/recipe_detail.html'

#About me page
def about(request):
    return render(request, "recipes/about_me.html")


@login_required
def search(request):
    # adds an instance of RecipesSearchForm
    form = RecipeSearchForm(request.POST or None)

    # Initializes dataframe to None
    recipes_df = None

    bar_chart = None
    pie_chart = None
    line_chart = None

    if request.method == "POST" and form.is_valid():
        # Retrieves the search criteria from the form
        search_by = form.cleaned_data.get("search_by")
        search_term = form.cleaned_data.get("search_term")
        cooking_time = form.cleaned_data.get("cooking_time")
        difficulty = form.cleaned_data.get("difficulty")

        # Filters the queryset based on the form input
        qs = Recipe.objects.all()

        if search_by == "name" and search_term:
            qs = qs.filter(name__icontains=search_term)
        elif search_by == "cooking_time" and cooking_time is not None:
            qs = qs.filter(cooking_time=cooking_time)
        elif search_by == "difficulty" and difficulty:
            qs = [recipe for recipe in qs if recipe.difficulty == difficulty]

        # Checks if the queryset is not empty
        if qs:
            # Converts list to pandas dataframe, else converts queryset to pandas DataFrame
            if isinstance(qs, list):
                recipes_df = pd.DataFrame([recipe.__dict__ for recipe in qs])
            else:
                recipes_df = pd.DataFrame(qs.values())

            recipes_df.index += 1

            # Retrieves each Recipe object using its id, then calls get_absolute_url() on it to generate the link
            def format_recipe_name_table(row):
                recipe = Recipe.objects.get(id=row["id"])
                return f"<a href='{recipe.get_absolute_url()}'>{row['name']}</a>"
            
            def format_recipe_name_chart(row):
                return row["name"]

            recipes_df["name_table"] = recipes_df.apply(format_recipe_name_table, axis=1)
            recipes_df["name_chart"] = recipes_df.apply(format_recipe_name_chart, axis=1)

            # Calculates difficulty and number of ingredients for each recipe
            recipes_df["difficulty"] = [recipe.difficulty for recipe in qs]
            recipes_df["number_of_ingredients"] = recipes_df["ingredients"].apply(lambda x: len(x.split(", ")))

            # Generate charts
            bar_chart = get_chart("#1", recipes_df, labels=recipes_df["name_chart"].values)
            pie_chart = get_chart("#2", recipes_df, labels=recipes_df["difficulty"].values)
            line_chart = get_chart("#3", recipes_df, labels=recipes_df["name_chart"].values)

            recipes_df = recipes_df[["name_table", "cooking_time", "difficulty"]]
            recipes_df = recipes_df.rename(columns={"name_table": "Name"})
            recipes_df = recipes_df.rename(columns={"cooking_time": "Cooking Time (minutes)"})
            recipes_df.columns = recipes_df.columns.str.capitalize()

            # Convert DataFrame to HTML for display
            recipes_df = recipes_df.to_html(escape=False)


    # Prepares data to send from view to template
    context = {
        "form": form,
        "recipes_df": recipes_df,
        "bar_chart": bar_chart,
        "pie_chart": pie_chart,
        "line_chart": line_chart,
    }

    # Loads page using "context" information
    return render(request, "recipes/recipe_search.html", context)

@login_required
def add_recipe(request):

    if request.method == "POST":
        new_recipe_form = NewRecipeForm(request.POST, request.FILES)

        if new_recipe_form.is_valid():
            new_recipe_form.save()
            return redirect("recipes:list")
        
    else:
        new_recipe_form = NewRecipeForm()

    context = {
        "new_recipe_form": new_recipe_form
    }

    return render(request, "recipes/add_recipe.html", context)

recipes/templates/recipes/about_me.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"> <!--The character set for the page-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../static/recipes/about.css">
    <title>
        About Me
    </title>
</head>

<body>
    <center>
        <div>
            <img src="../../static/recipes/images/about.jpg" alt="home" class="about_pic">
        </div>
        <div class="Nav">
            <a href="{% url 'recipes:list' %}" class="nav_btn">Recipe List</a>
            <a href="{%url 'logout' %}" class="nav_btn"> Logout </a>
        </div>
        <br />
        <h2>
            Thank you for using my App!
        </h2>
        <br />
        <div class="contact-box">
            <h3>Hi! I'm Matt and I hope you enjoyed using the app. If you
                want contact me or see more projects I've done,
                check out these links below:
            </h3>
            <div><b>Email:</b> mdainton21@gmail.com</div>
            <br />
            <div><b>GitHub:</b> https://github.com/mdainton21</div>
            <br />
            <div><b>Portfolio:</b> https://mdainton21.github.io/portfolio-website/</div>
            <br />
            <div>
                <img src="../../static/recipes/images/about2.jpg" alt="home" class="about_pic2">
            </div>

        </div>
    </center>

</body>

</html>

recipes/templates/recipes/add_recipe.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"> <!--The character set for the page-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../static/recipes/add.css">
    <title>
        Add Recipe
    </title>
</head>

<body>
    <center>
        <div class="pic_container">
            <img src="../../static/recipes/images/add_recipe.jpg" alt="add_recipe_header" class="add_pic">
        </div>
        <div class="Nav">
            <a href="{% url 'recipes:list' %}" class="nav_btn">Return to List</a>
            <a href="{% url 'recipes:about' %}" class="nav_btn">About Me</a>
            <a href="{%url 'logout' %}" class="nav_btn"> Logout </a>
        </div>
        <h2>All fields are required.</h2>

        {% if messages %} {% for message in messages %}
        <script>
            alert("{{ message }}");
        </script>
        {% endfor %} {% endif %}

        <div class="add-form">
            <form action="" method="POST" class="form_data" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="box">
                    <label for="id_name">Name:</label>
                    <input type="text" name="name" id="id_name" required>
                </div>

                <div class="box">
                    <label for="id_cooking_time">Cooking Time<br>(in minutes):</label>
                    <input type="number" name="cooking_time" id="id_cooking_time" required>
                </div>

                <div class="box">
                    <label for="id_ingredients">Ingredients:</label>
                    <textarea name="ingredients" id="id_ingredients" required></textarea>
                </div>

                <div class="box">
                    <label for="id_description">Description:</label>
                    <textarea name="description" id="id_description" required></textarea>
                </div>

                <div class="pic-box">
                    <label for="id_picture">Picture:</label>
                    <input type="file" name="pic" id="id_picture">
                </div>

                <button type="submit" class="create-btn">Add Recipe</button>
            </form>
        </div>
    </center>
</body>

</html>

recipes/templates/recipes/recipe_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"> <!--The character set for the page-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../static/recipes/detail.css">
    <title>
        Recipe Details
    </title>
</head>

<body class="detail_body">
    <center>
        <div class="details_box">
            <img src="{{object.pic.url}}" width="200" height="200"
                style="display: flex; margin-top: 5px; border: 5px solid #ffffff" />

            <h2> {{object.name}} </h2>

            <center>
                <table cellpadding="10">
                    <tr>
                        <td>
                            <b>Cooking time: </b> {{object.cooking_time}} minutes
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Ingredients: </b> {{object.ingredients}}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Difficulty: </b> {{object.difficulty}}
                        </td>
                    </tr>
                </table>
            </center>

            <p>{{object.description}} </p>
            <br>
            <a href="{% url 'recipes:list' %}" class="back_btn">Back to List</a>
            <a href="{%url 'logout' %}" class="logout_btn"> Logout </a>
        </div>
    </center>
</body>

</html>

recipes/templates/recipes/recipe_overview.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"> <!--The character set for the page-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../static/recipes/overview.css">
    <title>
        Recipe List
    </title>
</head>

<body>
    <div class="pic_container">
        <img src="../../static/recipes/images/recipe_list.jpg" alt="home" class="list_pic">
    </div>
    <center>
        <div class="Nav">
            <a href="{% url 'recipes:search' %}" class="logout_btn">Search for a Recipe</a>
            <a href="{% url 'recipes:add_recipe' %}" class="logout_btn">Add a Recipe</a>
            <a href="{% url 'recipes:about' %}" class="logout_btn">About Me</a>
            <a href="{%url 'logout' %}" class="logout_btn"> Logout </a>
        </div>
        <table border="1" cellpadding="5" cellspacing="2" width="800" height="150">
            {% for object in object_list %}
            <tr>

                <td align="center"><a href="{{object.get_absolute_url}}" class="recipe_link">
                        <b>{{object.name}}</b>
                    </a></td>

                <td>
                    <center><img src="{{object.pic.url}}" width="150" height="150" /></center>
                </td>

                <td align="center">
                    <p>{{object.description}}</p>
                </td>
            </tr>
            {% endfor %}
        </table>
    </center>
</body>

</html>

recipes/templates/recipes/recipe_search.html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8"> <!--The character set for the page-->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="../../static/recipes/search.css">
   <title>
      Recipe List
   </title>
</head>

<body>
   <center>
      <div class="pic_container">
         <img src="../../static/recipes/images/Search.jpg" alt="search_header" class="search_pic">
      </div>
      <div class="Nav">
         <a href="{% url 'recipes:list' %}" class="logout_btn">Return to List</a>
         <a href="{% url 'recipes:about' %}" class="logout_btn">About Me</a>
         <a href="{%url 'logout' %}" class="logout_btn"> Logout </a>
      </div>
      {% block content %}
      <h1>Search for recipes</h1>
   </center>

   <!-- Search form -->
   <div class="search-form">
      <form method="POST" novalidate>
         {% csrf_token %}

         <!-- Dropdown to select the search criterion -->
         {{ form.search_by.label_tag }} {{ form.search_by }}

         <!-- Div for inputting the recipe name, hidden by default -->
         <div id="search_term_div" style="display: none;">
            {{ form.search_term.label_tag }} {{ form.search_term }}
         </div>

         <!-- Div for inputting the cooking time, hidden by default -->
         <div id="cooking_time_div" style="display: none;">
            {{ form.cooking_time.label_tag }} {{ form.cooking_time }}
         </div>

         <!-- Div for selecting the difficulty, hidden by default -->
         <div id="difficulty_div" style="display: none;">
            {{ form.difficulty.label_tag }} {{ form.difficulty }}
         </div>

         <!-- Submit Button -->
         <center>
            <button type="submit">Search</button>
         </center>
      </form>
   </div>
   <center>
      <br>

      <!-- Checks if there is any data in recipes_df -->
      {% if recipes_df %}
      <h2 class="search-header">Search Results</h2>
      {{recipes_df | safe}}

      <br>

      <!-- Bar Chart -->
      <h3>Bar Chart: Cooking Time per Recipe</h3>
      <img class="chart-image" src="data:image/png;base64,{{ bar_chart }}" alt="Bar Chart">

      <!-- Pie Chart -->
      <h3>Pie Chart: Percentage of Recipe Difficulties</h3>
      <img class="chart-image" src="data:image/png;base64,{{ pie_chart }}" alt="Pie Chart">

      <!-- Line Chart -->
      <h3>Line Chart: Number of Ingredients per Recipe</h3>
      <img class="chart-image" src="data:image/png;base64,{{ line_chart }}" alt="Line Chart">

      {% else %}
      <h3>Try searching for a Recipe!</h3>
      {% endif %}

   </center>

   <script>
      document.addEventListener("DOMContentLoaded", function () {
         // Gets references to the form elements
         const searchByField = document.getElementById("id_search_by");
         const searchTermDiv = document.getElementById("search_term_div");
         const cookingTimeDiv = document.getElementById("cooking_time_div");
         const difficultyDiv = document.getElementById("difficulty_div");

         // Function to update the visibility of search input fields based on the selected criterion
         function updateSearchFields() {
            // Gets the selected value from the dropdown
            const searchByValue = searchByField.value;

            // Hide all search input fields by default
            searchTermDiv.style.display = "none";
            cookingTimeDiv.style.display = "none";
            difficultyDiv.style.display = "none";

            // Show the appropriate input field based on the selected search criterion
            if (searchByValue === "name") {
               searchTermDiv.style.display = "block";
            } else if (searchByValue === "cooking_time") {
               cookingTimeDiv.style.display = "block";
            } else if (searchByValue === "difficulty") {
               difficultyDiv.style.display = "block";
            }
         }

         // Add event listener to the dropdown to update search fields when the selected value changes
         searchByField.addEventListener("change", updateSearchFields);

         // Initial call to set the correct fields based on default or current selected value
         updateSearchFields();
      });
   </script>
   {% endblock %}
</body>

</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"> <!--The character set for the page-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="../../static/recipes/home.css">
    <title>
        Recipe List
    </title>
 </head>

<body>
    <center>
        <div>
            <img src="../../static/recipes/images/welcome.jpg" alt="home" class="welcome_pic">
        </div>
        <h1>
            Welcome to the Recipe App!
        </h1>
        <br />
        <h3>
            See our wide range of recipes, and maybe find something new for you to enjoy along the way!
        </h3>
        <br />

        <a href="{%url 'login' %}" class="login_btn"> Login </a>
    </center>

</body>

</html>